# Generated by Django 5.0.1 on 2026-02-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('memory_count', models.IntegerField(default=0)),
                ('messages_today', models.IntegerField(default=0)),
                ('last_message_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='memory_engine.botuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_preview', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('voice', 'Voice Note'), ('image', 'Image'), ('document', 'Document'), ('web', 'Web App')], default='whatsapp', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('chroma_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='memory_engine.botuser')),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
            },
        ),
    ]
