# Generated by Django 5.0.1 on 2026-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_engine', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='media_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
