# Generated by Django 5.0.1 on 2026-03-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_engine', '0004_calendarevent_dashboardtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('note', 'Note'), ('other', 'Other')], default='other', max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('caption', models.TextField(blank=True, default='')),
                ('ai_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_files', to='memory_engine.botuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
