# Generated by Django 5.0.1 on 2026-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_engine', '0005_savedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
    ]
