# Generated by Django 5.0.1 on 2026-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_engine', '0006_reminder_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_twilio_sid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
